appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: gUH9N5xUNB1K9FH2VwNvOIKDWFBjXISTkSPyupKpWbKSJfRESRDp+qij8Ek37xGvyWEWUwna65w8qsEDtblLpUIKdW15KZm0vmDvWgb6If/3i11L14DaxF9Le3qysiUs8+KidUrO2eHALCEhyy4TbmrlhO1sAGLURb/Ll7N8bnn9ortTtWD1np8QWiNTiLF8GfPLQ2N3qcPJhUjDxWJ+8k/wnE1hVqmvvDPye8x4IpoyYRN1aUgbnmyRuA6GVi6pGJYV++HLy5UaEl7JHCGyuXOfPJGhoZGiPUbiDzxDftR040YxILaXWcpVbHP4MyG/c2//UYUFP3VOJ21l8uPnt1hXrNMQJsKajQ4W0SJgPYzW5Ag2+dPB3swYsWuOSKvmfYk3ispx3be6qRVZrGtXcAJWQwJDJ+5nLt99IxRUzmSFbmfjeLe5fvRdQumPs76xstWmcB3ZtH056jl/aTSEWsNIGt7BmFgMJ3f+iEXjCUv2S1xtbNUeWJBICBp5JPXQFQKgBmfcO/Bnd7NhCccl7n9ceXu7ILm46cdDd/isxYifSrQaS4vxBIrHY1nBmVgVE4raTCD79T9DahMlM6EytOScQolET1AGrXCNRGw1nm3KeCIHor7qWoifxbEyLik8nJeqv1Ctmd2e1YPMwbRzC/mzWrQrfvCcc3KWLsoKMsA=}
